### ISSUE TITLE
Program GUI

### ISSUE THREAD

**Issue by JakeLion** [AbdulHpy/INST-Package-manager#1]
I have not looked at how this program performs so far, however I think it could benefit from a GUI. I think a lot of less experienced computer users may be using this software in the future, and there gonna think "oh its a virus"! I have some ideas for a GUI and I have some experience with GUI development, so if your interested, I would be happy to offer some changes to allow a GUI.

*note*: I do not plan for the GUI to change how the program actually works, my plan is that it will work as an input/output for the user.

**Comment by AbdulHpy** [comment]
Well it's not a bad idea but I don't really expect many new programmers to use this and at the moment it just reads a file and installs all the packages listed in the file using your preferred choice (pip, gem, npm, etc) so I never planned on really adding a gui but it's a good idea!

**Comment by JakeLion** [comment]
True, I just think it would add a level of professionalism and ease of use for people who are still frightened by command line-like visuals.

**Comment by AbdulHpy** [comment]
Can you send me a picture of what you have in mind?

**Comment by JakeLion** [comment]
![UI](https://user-images.githubusercontent.com/69877521/110051555-593db900-7d13-11eb-9b57-962722de1f0a.PNG)

You can see here it still looks a lot like a command shell however it has things like help, about, etc. It would even be possible to allow the user to enter in commands that have a really long name or use logs of arguments (if you ever add that).
Obviously I can make it look a lot better but this is what I threw together in about 15 minutes just to work as a demo.

Let me know what you think!

**Comment by AbdulHpy** [comment]
Well that's not a bad idea, it's a good suggestion and I might implement it

**Comment by JakeLion** [comment]
Sounds good, let me know if you have any other questions. Im gonna close this issue now if it isnt an issue.
